name: NT-Tweet-pls
on:
  push:
    branches:    
      - main

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps: 
    - name: Send Tweet Action
      uses: ethomson/send-tweet-action@v1.0.0
      with:
        # The status ("tweet") to post to twitter.
        status: 'Welcome to NT Git Bot, where we bring you a load of good commit messages. Like, ${{ github.event.head_commit.message }}' 
        consumer-key: ${{ secrets.TWITTER_CK }}
        consumer-secret: ${{ secrets.TWITTER_CS }}
        access-token: ${{ secrets.TWITTER_AT }}
        access-token-secret: ${{ secrets.TWITTER_AS }} # optional
