- name: Tweet action
  # You may pin to the exact commit or the version.
  # uses: snow-actions/tweet@d78243e356603937ebc80dd531d9f0e071adc3e3
  uses: snow-actions/tweet@v1.1.0
  with:
    # The text of the status update. URL encode as necessary. t.co link wrapping will affect character counts.
    status: 
    # Upload media path(s).
Size restrictions for uploading via API
  * Image 5MB
  * GIF 15MB
  * Video 15MB

    media_paths: # optional
# James, I am in (you can delete this later, I just fancied committing for a laugh)
